#version 430 core

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image1D predictedPosLUTTexture;
layout(rgba32f, binding = 1) uniform image1D densityViscosityTexture;
layout(rgba32f, binding = 2) uniform image1D posvelTexture;

uniform int nr_particles;
uniform float smoothing_radius;
uniform int LUT_P1;
uniform int LUT_P2;
uniform int LUT_P3;
uniform int LUT_P4;
uniform int LUT_P5;

uniform float water_mass;
uniform float density_smoothing_kernel_volume;
uniform float near_density_smoothing_kernel_volume;
uniform float viscosity_smoothing_kernel_volume;

uniform float viscosity_strength;

int computeHash(int x, int y) {
	x += LUT_P4;
	y += LUT_P5;
	return abs(x * LUT_P1 + y * LUT_P2 + LUT_P3) % nr_particles;
}

int computeHash(vec2 pos) {
	int hash_x = int(pos.x / smoothing_radius);
	int hash_y = int(pos.y / smoothing_radius);
	return computeHash(hash_x, hash_y);
}	

float densitySmoothingKernel(float dist) {
	float tmp = max(0.0, smoothing_radius - dist);
	float ans = pow(tmp, 3.0) * water_mass;
	ans /= density_smoothing_kernel_volume;
	return ans;
}
	
float nearDensitySmoothingKernel(float dist) {
	float tmp = max(0.0, smoothing_radius - dist);
	float ans = pow(tmp, 6.0) * water_mass;
	ans /= near_density_smoothing_kernel_volume;
	return ans;
}
	
float viscositySmoothingKernel(float dist) {
	float tmp = max(0.0, smoothing_radius * smoothing_radius - dist * dist);
	float ans = pow(tmp, 3.0);
	ans /= viscosity_smoothing_kernel_volume;
	return ans;
}

const int dx[9] = int[9](-1, -1, -1, 0, 0, 0, 1, 1, 1);
const int dy[9] = int[9](-1, 0, 1, -1, 0, 1, -1, 0, 1);

vec2 computeDensity(vec2 pos) {
	float density = 0;
	float near_density = 0;
	int hash_x = int(pos.x / smoothing_radius);
	int hash_y = int(pos.y / smoothing_radius);
	for(int i = 0; i < 9; i++){
		int nx = hash_x + dx[i];
		int ny = hash_y + dy[i];
		int nhash = computeHash(nx, ny);
		int start_ind = int(imageLoad(predictedPosLUTTexture, nhash).w);
		for(int j = start_ind; j < nr_particles; j++){
			vec4 lut = imageLoad(predictedPosLUTTexture, j);
			vec2 cpos = lut.xy;
			int chash = int(lut.z);
			if(chash != nhash) {
				break;
			}
			density += densitySmoothingKernel(distance(pos, cpos));
			near_density += nearDensitySmoothingKernel(distance(pos, cpos));
		}
	}
	return vec2(density, near_density);
}

vec2 computeViscosityForce(int ind, vec2 pos, vec2 vel) {
	vec2 viscosity_force = vec2(0);
	int hash_x = int(pos.x / smoothing_radius);
	int hash_y = int(pos.y / smoothing_radius);
	for(int i = 0; i < 9; i++){
		int nx = hash_x + dx[i];
		int ny = hash_y + dy[i];
		int nhash = computeHash(nx, ny);
		int start_ind = int(imageLoad(predictedPosLUTTexture, nhash).w);
		for(int j = start_ind; j < nr_particles; j++){
			vec4 lut = imageLoad(predictedPosLUTTexture, j);
			vec2 cpos = lut.xy;
			int chash = int(lut.z);
			if(chash != nhash) {
				break;
			}
			if(j == ind) {
				continue;
			}
			vec2 cvel = imageLoad(posvelTexture, j).zw;
			float dist = distance(pos, cpos);
			float influence = viscositySmoothingKernel(dist);
			viscosity_force += (cvel - vel) * influence;
		}
	}
	viscosity_force *= viscosity_strength;
	return viscosity_force;
}

void main() {
	int texelCoord = int(gl_GlobalInvocationID.x);
	
	vec4 predictedPosLUT = imageLoad(predictedPosLUTTexture, texelCoord);
	vec2 predicted_pos = predictedPosLUT.xy;
	
	vec2 ret = computeDensity(predicted_pos);
	float density = ret.x;
	float near_density = ret.y;
	
	//density = min(10.0, density);
	//near_density = min(10.0, near_density);
	
	vec4 posvel = imageLoad(posvelTexture, texelCoord);
	vec2 pos = posvel.xy;
	vec2 vel = posvel.zw;
	vec2 viscosity_force = computeViscosityForce(texelCoord, pos, vel);
	
	imageStore(densityViscosityTexture, texelCoord, vec4(density, near_density, viscosity_force));
}