#version 430 core

//Pipeline (2)
// - take prefix sum of gaussian start buffer using Blelloch scan
//   https://developer.nvidia.com/gpugems/gpugems3/part-vi-gpu-computing/chapter-39-parallel-prefix-sum-scan-cuda

//Blelloch scan is parallel algorithm to construct the exclusive prefix sum in place in a buffer. 
//it operates in two phases: upsweep and downsweep
// - upsweep replaces A[i] with sum[i - lb(i), i], where lb(x) = 2^{amount of leading 1s in binary representation of x} - 1
// - downsweep replaces each element with the exclusive prefix sum. 

//also, the algorithm is nicest to implement when the array size is a power of 2. 
//we can just pad out the array until its a power of 2. 

//ofc we'll want all our data in shared memory, so we'll break the buffer into B element blocks, each requiring B/2 threads. 
//first for each block compute the prefix sum for each block, and write the total sum for each block into another buffer. 
//then compute the prefix sum over all the blocks. 
//finally, for each block just add the sum of all the previous blocks to every element. 
//if the number of blocks ever exceeds B then we may be in trouble, but we can just set a limitation for now that the buffer
// is limited to at most B^2 elements. For B = 1024, we'll probably have to do some more optimizations before this becomes an issue.

layout (local_size_x = 512, local_size_y = 1, local_size_z = 1) in;

const int SWEEP_ITERS = 10;
const int BLOCK_SIZE = 1 << 10;	// 1024

uniform int scanPhase;

layout (binding = 1) buffer mainBuffer {
	int mainData[];
};

layout (binding = 2) buffer blockBuffer {
	int blockData[];
};

shared int localData[BLOCK_SIZE];

void main() {
	int local_id = int(gl_LocalInvocationID.x);
	int global_id = int(gl_GlobalInvocationID.x);
	int block_id = int(gl_WorkGroupID.x);
	
	if(scanPhase == 1) {		//compute per-block prefix sums
		//load elements into shared memory
		localData[local_id * 2 + 0] = mainData[block_id * BLOCK_SIZE + local_id * 2 + 0];
		localData[local_id * 2 + 1] = mainData[block_id * BLOCK_SIZE + local_id * 2 + 1];
		barrier();
	
		//upsweep
		for(int ival = 1; ival < BLOCK_SIZE; ival <<= 1) {
			if((local_id & (ival - 1)) == (ival - 1)) {
				localData[local_id * 2 + 1] += localData[local_id * 2 + 1 - ival];
			}
			barrier();
		}
		
		//downsweep
		int sum = 0;
		if(local_id == 0) {
			sum = localData[BLOCK_SIZE - 1];
			localData[BLOCK_SIZE - 1] = 0;
		}
		barrier();
		
		for(int ival = (BLOCK_SIZE >> 1); ival >= 1; ival >>= 1) {
			if((local_id & (ival - 1)) == (ival - 1)) {
				int tmp = localData[local_id * 2 + 1];
				localData[local_id * 2 + 1] += localData[local_id * 2 + 1 - ival];
				localData[local_id * 2 + 1 - ival] = tmp;
			}
			barrier();
		}
		
		//write elements back to global memory
		mainData[block_id * BLOCK_SIZE + local_id * 2 + 0] = localData[local_id * 2 + 0];
		mainData[block_id * BLOCK_SIZE + local_id * 2 + 1] = localData[local_id * 2 + 1];
		if(local_id == 0) {
			blockData[block_id] = sum;
		}
	}
	else if(scanPhase == 2) {	//compute block prefix sums
		//load elements into shared memory
		localData[local_id * 2 + 0] = blockData[local_id * 2 + 0];
		localData[local_id * 2 + 1] = blockData[local_id * 2 + 1];
		barrier();
		
		//upsweep
		for(int ival = 1; ival < BLOCK_SIZE; ival <<= 1) {
			if((local_id & (ival - 1)) == (ival - 1)) {
				localData[local_id * 2 + 1] += localData[local_id * 2 + 1 - ival];
			}
			barrier();
		}
		
		//downsweep
		if(local_id == 0) {
			localData[BLOCK_SIZE - 1] = 0;
		}
		barrier();
		
		for(int ival = (BLOCK_SIZE >> 1); ival >= 1; ival >>= 1) {
			if((local_id & (ival - 1)) == (ival - 1)) {
				int tmp = localData[local_id * 2 + 1];
				localData[local_id * 2 + 1] += localData[local_id * 2 + 1 - ival];
				localData[local_id * 2 + 1 - ival] = tmp;
			}
			barrier();
		}
		
		//write elements back to global memory
		blockData[local_id * 2 + 0] = localData[local_id * 2 + 0];
		blockData[local_id * 2 + 1] = localData[local_id * 2 + 1];
	}
	else if(scanPhase == 3) {	//add block prefix sums to all elements
		mainData[block_id * BLOCK_SIZE + local_id * 2 + 0] += blockData[block_id];
		mainData[block_id * BLOCK_SIZE + local_id * 2 + 1] += blockData[block_id];
	}
}
