#version 430 core

//Pipeline (5)
// - compute for each screen tile, its starting index within the sorted tile buffer

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

uniform int nrScreenTiles;
uniform int nrGaussians;

struct Tile {
	// tile_id should be in range [0, 65536)
	// gaussian_depth should be quantized in range [0, 65536)
	uint sort_key;		// (tile_id << 16) | (gaussian_depth << 0)
	int gaussian_id;
};

layout (binding = 1) readonly buffer gaussianStartBuffer {
	int gaussianStartData[];
};

layout (binding = 2) readonly buffer tileBuffer {
	Tile tileData[];
};

layout (binding = 5) buffer tileStartBuffer {
	int tileStartData[];
};

void main() {
	int tile_id = int(gl_GlobalInvocationID.x);
	if(tile_id >= nrScreenTiles) {
		return;
	}
	
	int total_tiles = gaussianStartData[nrGaussians];
	if(tile_id == 0) {	//sentinel tile
		tileStartData[nrScreenTiles] = total_tiles;
	}
	
	//binary search for first tile with id >= current tile
	int low = 0, high = total_tiles - 1;
	int ans = total_tiles;
	while(low <= high) {
		int mid = low + (high - low) / 2;
		int mid_tile_id = int(tileData[mid].sort_key >> 16) & 0xFFFF;
		if(mid_tile_id >= tile_id) {
			ans = mid;
			high = mid - 1;
		}
		else {
			low = mid + 1;
		}
	}
	tileStartData[tile_id] = ans;
}
