#version 430 core

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

struct Particle {
	vec2 pos;
	vec2 pred_pos;
	vec2 vel;
	int hash;
};

layout(binding = 0) buffer particleBuffer {
	Particle[] particleData;
};

layout(binding = 1) buffer hashLUTBuffer {
	int[] hashLUT;
};

struct ParticleInfo {
    vec2 visc_force;
    float density;
    float near_density;
};

layout(binding = 2) buffer particleInfoBuffer {
	ParticleInfo[] particleInfoData;
};

struct Obstacle {
	vec2 offset;
	vec2 dimensions;
};

layout(binding = 3) buffer obstacleBuffer {
	Obstacle[] obstacleData;
};

shared Particle local_particle_data[gl_WorkGroupSize.x];
shared ParticleInfo local_particle_info_data[gl_WorkGroupSize.x];

uniform float dt;
uniform vec2 gravity;
uniform int nr_particles;

uniform vec2 bounds_min;
uniform vec2 bounds_max;

uniform float smoothing_radius;
uniform int hash_mod;
uniform int LUT_P1;
uniform int LUT_P2;
uniform int LUT_P3;
uniform int LUT_P4;
uniform int LUT_P5;

uniform float density_smoothing_kernel_volume;
uniform float near_density_smoothing_kernel_volume;
uniform float viscosity_smoothing_kernel_volume;

uniform float target_density;
uniform float pressure_multiplier;
uniform float near_pressure_multiplier;

uniform int nr_obstacles;

int computeHash(int x, int y) {
	x += LUT_P1;
	y += LUT_P2;
	return abs(x * LUT_P3 + y * LUT_P4 + LUT_P5) % hash_mod;
}

int computeHash(ivec2 h) {
	return computeHash(h.x, h.y);
}

int computeHash(vec2 pos) {
	return computeHash(ivec2(floor(pos / smoothing_radius)));
}

float densitySmoothingKernelSlope(float dist) {
	return -3.0 * pow(max(0.0, smoothing_radius - dist), 2.0);
}

float nearDensitySmoothingKernelSlope(float dist) {
	return -6.0 * pow(max(0.0, smoothing_radius - dist), 5.0);
}

float densitySmoothingKernel(float dist) {
	float tmp = max(0.0, smoothing_radius - dist);
	float ans = pow(tmp, 3.0);
	ans /= density_smoothing_kernel_volume;
	return ans;
}

float nearDensitySmoothingKernel(float dist) {
	float tmp = max(0.0, smoothing_radius - dist);
	float ans = pow(tmp, 6.0);
	ans /= near_density_smoothing_kernel_volume;
	return ans;
}

vec2 calculatePressure(float density, float near_density) {
	float density_error = density - target_density;
	float pressure = density_error * pressure_multiplier;
	float near_pressure = near_density * near_pressure_multiplier;
	return vec2(pressure, near_pressure);
}

vec2 calculateSharedPressure(vec2 d1, vec2 d2) {
	vec2 p1 = calculatePressure(d1.x, d1.y);
	vec2 p2 = calculatePressure(d2.x, d2.y);
	return vec2((p1.x + p2.x) / 2.0, (p1.y + p2.y) / 2.0);
}

const ivec2 d_hpos[9] = ivec2[9] (
	ivec2(1, 1), ivec2(1, 0), ivec2(1, -1),
	ivec2(0, 1), ivec2(0, 0), ivec2(0, -1),
	ivec2(-1, 1), ivec2(-1, 0), ivec2(-1, -1)
);

Particle getParticle(int ind, int local_particle_start) {
	if(ind >= local_particle_start && ind < local_particle_start + gl_WorkGroupSize.x) {
		return local_particle_data[ind - local_particle_start];
	}
	return particleData[ind];
}

ParticleInfo getParticleInfo(int ind, int local_particle_start) {
	if(ind >= local_particle_start && ind < local_particle_start + gl_WorkGroupSize.x) {
		return local_particle_info_data[ind - local_particle_start];
	}
	return particleInfoData[ind];
}

void main() {
	int global_id = int(gl_GlobalInvocationID.x);
	int local_id = int(gl_LocalInvocationID.x);
	int local0_id = int(gl_WorkGroupID.x) * int(gl_WorkGroupSize.x);

	Particle p = particleData[global_id];
	ParticleInfo p_info = particleInfoData[global_id];
	vec2 p_density = vec2(p_info.density, p_info.near_density);
	
	ivec2 pred_hpos = ivec2(floor(p.pred_pos / smoothing_radius));
	ivec2 local0_hpos = ivec2(floor(particleData[local0_id].pred_pos / smoothing_radius));
	
	//compute pressure force
	vec2 pressure_force = vec2(0);
	for(int i = 0; i < 9; i++){
		//put stuff into local mem
		int local0_hash = computeHash(local0_hpos + d_hpos[i]);
		int local0_start = hashLUT[local0_hash];
		
		if(local0_start + local_id < nr_particles) {
			local_particle_data[local_id] = particleData[local0_start + local_id];
			local_particle_info_data[local_id] = particleInfoData[local0_start + local_id];
		}
		barrier();
		
		//compute contribution to pressure force
		int pred_hash = computeHash(pred_hpos + d_hpos[i]);
		int pred_start = hashLUT[pred_hash];
		for(int j = pred_start; j < nr_particles; j++){
			if(j == global_id) {
				continue;
			}
			Particle next = getParticle(j, local0_start);
			ParticleInfo next_info = getParticleInfo(j, local0_start);
			if(next.hash != pred_hash) {
				break;
			}
			
			vec2 next_density = vec2(next_info.density, next_info.near_density);
			float dist = distance(p.pred_pos, next.pred_pos);
			vec2 dir = p.pred_pos - next.pred_pos;
			if(dist == 0){
				dir = vec2(1, 0);
			}
			else {
				dir = normalize(dir);
			}
			float density_slope = densitySmoothingKernelSlope(dist);
			float near_density_slope = nearDensitySmoothingKernelSlope(dist);
			vec2 shared_pressure = calculateSharedPressure(p_density, next_density);
			pressure_force -= dir * ((shared_pressure.x * density_slope / p_density.x) + (shared_pressure.y * near_density_slope / p_density.y));
		}
		barrier();
	}
	
	
	vec2 viscosity_force = p_info.visc_force;
	vec2 gravity_force = gravity;
	vec2 boundary_force = vec2(0);
	
	//boundary clamping
	{
		if (p.pos.x < bounds_min.x + 0.001) {
			p.pos.x = bounds_min.x + 0.001;
			p.vel.x *= -0.1;
		}
		if (p.pos.x > bounds_max.x - 0.001) {
			p.pos.x = bounds_max.x - 0.001;
			p.vel.x *= -0.1;
		}
		if (p.pos.y < bounds_min.y + 0.001) {
			p.pos.y = bounds_min.y + 0.001;
			p.vel.y *= -0.1;
		}
		if (p.pos.y > bounds_max.y - 0.001) {
			p.pos.y = bounds_max.y - 0.001;
			p.vel.y *= -0.1;
		}
	}
	
	//boundary forces
	{
		if(p.pos.x - bounds_min.x < smoothing_radius) {
			boundary_force -= nearDensitySmoothingKernelSlope(p.pos.x - bounds_min.x) * vec2(1, 0);
		}
		if(bounds_max.x - p.pos.x < smoothing_radius) {
			boundary_force -= nearDensitySmoothingKernelSlope(bounds_max.x - p.pos.x) * vec2(-1, 0);
		}
		if(p.pos.y - bounds_min.y < smoothing_radius) {
			boundary_force -= nearDensitySmoothingKernelSlope(p.pos.y - bounds_min.y) * vec2(0, 1);
		}
		if(bounds_max.y - p.pos.y < smoothing_radius) {
			boundary_force -= nearDensitySmoothingKernelSlope(bounds_max.y - p.pos.y) * vec2(0, -1);
		}
	}
	
	//do obstacle collisions
	for(int i = 0; i < nr_obstacles; i++){
		Obstacle o = obstacleData[i];
		vec2 o_min = o.offset + bounds_min;
		vec2 o_max = o_min + o.dimensions;
		
		//if we're inside, clamp to nearest outside side
		if(o_min.x < p.pos.x && p.pos.x < o_max.x && o_min.y < p.pos.y && p.pos.y < o_max.y) {
			float d_xmin = p.pos.x - o_min.x;
			float d_xmax = o_max.x - p.pos.x;
			float d_ymin = p.pos.y - o_min.y;
			float d_ymax = o_max.y - p.pos.y;
			if(min(d_xmin, d_xmax) < min(d_ymin, d_ymax)) {
				p.vel.x *= -0.1;
				if(d_xmin < d_xmax) {
					p.pos.x = o_min.x - 0.001;
				}
				else {
					p.pos.x = o_max.x + 0.001;
				}
			}
			else {
				p.vel.y *= -0.1;
				if(d_ymin < d_ymax) {
					p.pos.y = o_min.y - 0.001;
				}
				else {
					p.pos.y = o_max.y + 0.001;
				}
			}
		}
		
		//apply a small boundary force 
		
	}
	
	vec2 force = pressure_force + viscosity_force + gravity_force + boundary_force * 0.1;
	p.vel += force * dt;
	
	particleData[global_id] = p;
}






