#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct Particle {
	vec3 pos;
	vec3 vel;
	int hash;
};

layout(binding = 0) buffer particleBuffer {
	Particle[] particleData;
};

uniform float dt;

uniform float smoothing_radius;
uniform int hash_mod;
uniform int LUT_P1;
uniform int LUT_P2;
uniform int LUT_P3;
uniform int LUT_P4;
uniform int LUT_P5;
uniform int LUT_P6;
uniform int LUT_P7;

int computeHash(int x, int y, int z) {
	x += LUT_P1;
	y += LUT_P2;
	z += LUT_P3;
	return abs(x * LUT_P4 + y * LUT_P5 + z * LUT_P6 + LUT_P7) % hash_mod;
}

int computeHash(ivec3 h) {
	return computeHash(h.x, h.y, h.z);
}

int computeHash(vec3 pos) {
	return computeHash(ivec3(floor(pos / smoothing_radius)));
}

void main() {
	int particle_id = int(gl_GlobalInvocationID.x);
	Particle p = particleData[particle_id];
	
	//update position
	p.pos += p.vel * dt;
	
	p.hash = computeHash(p.pos.xyz);

	particleData[particle_id] = p;
}
