#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct Particle {
	vec3 pos;
	vec3 vel;
	vec3 pred_pos;
	vec3 visc_force;
	int hash;
	int hash_start_ind;
	float density;
	float near_density;
};

layout(binding = 0) buffer particleBuffer {
	Particle[] particleData;
};

uniform float dt;
uniform vec3 bounds_min;
uniform vec3 bounds_max;
uniform vec3 gravity;
uniform float boundary_restitution;

uniform float smoothing_radius;
uniform int hash_mod;
uniform int LUT_P1;
uniform int LUT_P2;
uniform int LUT_P3;
uniform int LUT_P4;
uniform int LUT_P5;
uniform int LUT_P6;

int computeHash(int x, int y, int z) {
	x += LUT_P1;
	y += LUT_P2;
	z += LUT_P3;
	return abs(x * LUT_P4 + y * LUT_P5 + z * LUT_P6) % hash_mod;
}

int computeHash(vec3 pos) {
	int hash_x = int(pos.x / smoothing_radius);
	int hash_y = int(pos.y / smoothing_radius);
	int hash_z = int(pos.z / smoothing_radius);
	return computeHash(hash_x, hash_y, hash_z);
}

void main() {
	int particle_id = int(gl_GlobalInvocationID.x);
	Particle p = particleData[particle_id];
	
	//update position
	p.pos += p.vel * dt;
	
	//gravity
	p.vel += gravity * dt;
	
	//boundary collisions
	{
		if (p.pos.x < bounds_min.x) {
			p.pos.x = bounds_min.x;
			p.vel.x *= -boundary_restitution;
		}
		if (p.pos.x > bounds_max.x) {
			p.pos.x = bounds_max.x;
			p.vel.x *= -boundary_restitution;
		}
		if (p.pos.y < bounds_min.y) {
			p.pos.y = bounds_min.y;
			p.vel.y *= -boundary_restitution;
		}
		if (p.pos.y > bounds_max.y) {
			p.pos.y = bounds_max.y;
			p.vel.y *= -boundary_restitution;
		}
		if (p.pos.z < bounds_min.z) {
			p.pos.z = bounds_min.z;
			p.vel.z *= -boundary_restitution;
		}
		if (p.pos.z > bounds_max.z) {
			p.pos.z = bounds_max.z;
			p.vel.z *= -boundary_restitution;
		}
	}
	
	p.hash = computeHash(p.pos);
	
	particleData[particle_id] = p;
}
