#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct Particle {
	vec3 pos;
	vec3 vel;
	
};

layout(binding = 0) buffer posBuffer {
	vec4[] posData;
};

layout(binding = 1) buffer velBuffer {
	vec4[] velData;
};

layout(binding = 2) buffer hashBuffer {
	int[] hashData;
};

uniform float dt;
uniform vec3 bounds_min;
uniform vec3 bounds_max;
uniform vec3 gravity;
uniform float boundary_restitution;

uniform int hash_mod;
uniform float smoothing_radius;
uniform int LUT_P1;
uniform int LUT_P2;
uniform int LUT_P3;
uniform int LUT_P4;
uniform int LUT_P5;
uniform int LUT_P6;
uniform int LUT_P7;

int computeHash(int x, int y, int z) {
	x += LUT_P1;
	y += LUT_P2;
	z += LUT_P3;
	return abs(x * LUT_P4 + y * LUT_P5 + z * LUT_P6 + LUT_P7) % hash_mod;
}

int computeHash(vec3 pos) {
	int hash_x = int(pos.x / smoothing_radius);
	int hash_y = int(pos.y / smoothing_radius);
	int hash_z = int(pos.z / smoothing_radius);
	return computeHash(hash_x, hash_y, hash_z);
}

void main() {
	int particle_id = int(gl_GlobalInvocationID.x);
	vec3 pos = posData[particle_id].xyz;
	vec3 vel = velData[particle_id].xyz;
	
	//update position
	pos += vel * dt;
	
	//gravity
	vel += gravity * dt;
	
	//boundary collisions
	{
		if (pos.x < bounds_min.x) {
			pos.x = bounds_min.x;
			vel.x *= -boundary_restitution;
		}
		if (pos.x > bounds_max.x) {
			pos.x = bounds_max.x;
			vel.x *= -boundary_restitution;
		}
		if (pos.y < bounds_min.y) {
			pos.y = bounds_min.y;
			vel.y *= -boundary_restitution;
		}
		if (pos.y > bounds_max.y) {
			pos.y = bounds_max.y;
			vel.y *= -boundary_restitution;
		}
		if (pos.z < bounds_min.z) {
			pos.z = bounds_min.z;
			vel.z *= -boundary_restitution;
		}
		if (pos.z > bounds_max.z) {
			pos.z = bounds_max.z;
			vel.z *= -boundary_restitution;
		}
	}
	
	posData[particle_id].xyz = pos;
	velData[particle_id].xyz = vel;
	hashData[particle_id * 4 + 0] = computeHash(pos);
}
