#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct Particle {
	vec3 pos;
	vec3 vel;
	int hash;
};

layout(binding = 0) buffer particleBuffer {
	Particle[] particleData;
};

layout(binding = 1) buffer hashLUTBuffer {
	int[] hashLUT;
};

struct ParticleInfo {
	vec3 pred_pos;
	float density;
	vec3 visc_force;
	float near_density;
};	

layout(binding = 2) buffer particleInfoBuffer {
	ParticleInfo[] particleInfoData;
};

uniform float dt;
uniform int nr_particles;

uniform float smoothing_radius;
uniform int hash_mod;
uniform int LUT_P1;
uniform int LUT_P2;
uniform int LUT_P3;
uniform int LUT_P4;
uniform int LUT_P5;
uniform int LUT_P6;
uniform int LUT_P7;

uniform float density_smoothing_kernel_volume;
uniform float near_density_smoothing_kernel_volume;
uniform float viscosity_smoothing_kernel_volume;

uniform float viscosity_strength;
uniform float predict_delta_time;

int computeHash(int x, int y, int z) {
	x += LUT_P1;
	y += LUT_P2;
	z += LUT_P3;
	return abs(x * LUT_P4 + y * LUT_P5 + z * LUT_P6 + LUT_P7) % hash_mod;
}

int computeHash(vec3 pos) {
	int hash_x = int(pos.x / smoothing_radius);
	int hash_y = int(pos.y / smoothing_radius);
	int hash_z = int(pos.z / smoothing_radius);
	return computeHash(hash_x, hash_y, hash_z);
}

float densitySmoothingKernel(float dist) {
	float tmp = max(0.0, smoothing_radius - dist);
	float ans = pow(tmp, 3.0);
	ans /= density_smoothing_kernel_volume;
	return ans;
}
	
float nearDensitySmoothingKernel(float dist) {
	float tmp = max(0.0, smoothing_radius - dist);
	float ans = pow(tmp, 6.0);
	ans /= near_density_smoothing_kernel_volume;
	return ans;
}
	
float viscositySmoothingKernel(float dist) {
	float tmp = max(0.0, smoothing_radius * smoothing_radius - dist * dist);
	float ans = pow(tmp, 3.0);
	ans /= viscosity_smoothing_kernel_volume;
	return ans;
}

const int dx[27] = int[27](-1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1);
const int dy[27] = int[27](-1, -1, -1, 0, 0, 0, 1, 1, 1, -1, -1, -1, 0, 0, 0, 1, 1, 1, -1, -1, -1, 0, 0, 0, 1, 1, 1);
const int dz[27] = int[27](-1, 0, 1, -1, 0, 1, -1, 0, 1, -1, 0, 1, -1, 0, 1, -1, 0, 1, -1, 0, 1, -1, 0, 1, -1, 0, 1);

vec2 computeDensity(vec3 pos) {
	float density = 0;
	float near_density = 0;
	int hash_x = int(pos.x / smoothing_radius);
	int hash_y = int(pos.y / smoothing_radius);
	int hash_z = int(pos.z / smoothing_radius);
	for(int i = 0; i < 27; i++){
		int nx = hash_x + dx[i];
		int ny = hash_y + dy[i];
		int nz = hash_z + dz[i];
		int nhash = computeHash(nx, ny, nz);
		int start_ind = hashLUT[nhash];
		for(int j = start_ind; j < nr_particles; j++){
			int chash = particleData[j].hash;
			if(chash != nhash) {
				break;
			}
			vec3 cpos = particleData[j].pos;
			density += densitySmoothingKernel(distance(pos, cpos));
			near_density += nearDensitySmoothingKernel(distance(pos, cpos));
		}
	}
	return vec2(density, near_density);
}

vec3 computeViscosityForce(int particle_id, vec3 pos, vec3 vel) {
	vec3 viscosity_force = vec3(0);
	int hash_x = int(pos.x / smoothing_radius);
	int hash_y = int(pos.y / smoothing_radius);
	int hash_z = int(pos.z / smoothing_radius);
	for(int i = 0; i < 27; i++){
		int nx = hash_x + dx[i];
		int ny = hash_y + dy[i];
		int nz = hash_z + dz[i];
		int nhash = computeHash(nx, ny, nz);
		int start_ind = hashLUT[nhash];
		for(int j = start_ind; j < nr_particles; j++){
			int chash = particleData[j].hash;
			if(chash != nhash) {
				break;
			}
			if(j == particle_id) {
				continue;
			}
			vec3 cpos = particleData[j].pos;
			vec3 cvel = particleData[j].vel;
			float dist = distance(pos, cpos);
			float influence = viscositySmoothingKernel(dist);
			viscosity_force += (cvel - vel) * influence;
		}
	}
	viscosity_force *= viscosity_strength;
	return viscosity_force;
}

void main() {
	int particle_id = int(gl_GlobalInvocationID.x);
	Particle p = particleData[particle_id];
	ParticleInfo p_info = particleInfoData[particle_id];
	
	p_info.pred_pos = p.pos + p.vel * dt;
	vec2 dvec = computeDensity(p_info.pred_pos);
	p_info.density = dvec.x;
	p_info.near_density = dvec.y;
	p_info.visc_force = computeViscosityForce(particle_id, p.pos, p.vel);
	
	particleInfoData[particle_id] = p_info;
}






