#version 430 core

layout (local_size_x = 512, local_size_y = 1, local_size_z = 1) in;

struct Particle {
	vec3 pos;
	vec3 vel;
	int hash;
};

layout(binding = 0) buffer particleBuffer {
	Particle[] particleData;
};

shared Particle local_data[gl_WorkGroupSize.x * 2];

uniform int mode;
uniform int global_op_sz;

//ensures that particle a has less hash than b
void globalCompareAndSwap(int a, int b) {
	if(particleData[b].hash < particleData[a].hash) {		
		Particle tmp = particleData[a];
		particleData[a] = particleData[b];
		particleData[b] = tmp;
	}
}

void globalFlip(int op_sz, int id) {
	int offset = ((2 * id) / op_sz) * op_sz;
	globalCompareAndSwap(offset + (id % (op_sz / 2)), offset + op_sz - (id % (op_sz / 2)) - 1);
}	

void globalDisperse(int op_sz, int id) {
	int offset = ((2 * id) / op_sz) * op_sz;
	globalCompareAndSwap(offset + (id % (op_sz / 2)), offset + (op_sz / 2) + (id % (op_sz / 2)));
}

void localCompareAndSwap(int a, int b) {
	if(local_data[b].hash < local_data[a].hash) {		
		Particle tmp = local_data[a];
		local_data[a] = local_data[b];
		local_data[b] = tmp;
	}
}

void localFlip(int op_sz, int id) {
	int offset = ((2 * id) / op_sz) * op_sz;
	localCompareAndSwap(offset + (id % (op_sz / 2)), offset + op_sz - (id % (op_sz / 2)) - 1);
}	

void localDisperse(int op_sz, int id) {
	int offset = ((2 * id) / op_sz) * op_sz;
	localCompareAndSwap(offset + (id % (op_sz / 2)), offset + (op_sz / 2) + (id % (op_sz / 2)));
}

void main() {
	int global_id = int(gl_GlobalInvocationID.x);
	int local_id = int(gl_LocalInvocationID.x);
	
	int offset = int(gl_WorkGroupSize.x * 2 * gl_WorkGroupID.x);
	
	if(mode == 0){	//local bms
		local_data[local_id * 2] = particleData[offset + local_id * 2];
		local_data[local_id * 2 + 1] = particleData[offset + local_id * 2 + 1];
		barrier();
		
		for(int i = 2; i <= gl_WorkGroupSize.x * 2; i *= 2){
			localFlip(i, local_id);
			barrier();
			for(int j = i / 2; j > 1; j /= 2){
				localDisperse(j, local_id);
				barrier();
			}
		}
		
		particleData[offset + local_id * 2] = local_data[local_id * 2];
		particleData[offset + local_id * 2 + 1] = local_data[local_id * 2 + 1];
	}
	else if(mode == 1){	//local disperse
		local_data[local_id * 2] = particleData[offset + local_id * 2];
		local_data[local_id * 2 + 1] = particleData[offset + local_id * 2 + 1];
		barrier();
		
		for(int j = int(gl_WorkGroupSize.x); j > 1; j /= 2){
			localDisperse(j, local_id);
			barrier();
		}
		
		particleData[offset + local_id * 2] = local_data[local_id * 2];
		particleData[offset + local_id * 2 + 1] = local_data[local_id * 2 + 1];
	}
	else if(mode == 2){	//big flip
		globalFlip(global_op_sz, global_id);
	}
	else if(mode == 3){	//big disperse
		globalDisperse(global_op_sz, global_id);
	}
}
