#version 430 core
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) buffer posBuffer {
	vec3[] posData;
};

layout(binding = 1) buffer tetIndBuffer {
	ivec4[] tetIndData;
};

layout(binding = 2) buffer baryCoordBuffer {
	vec4[] baryCoordData;
};

layout(binding = 3) buffer outPosBuffer {
	float[] outPosData;
};

void main() {
	int vertex_id = int(gl_GlobalInvocationID.x);
	vec4 bary = baryCoordData[vertex_id];
	ivec4 tet = tetIndData[vertex_id];
	
	vec3 pos = vec3(0);
	pos += posData[tet.x] * bary.x;
	pos += posData[tet.y] * bary.y;
	pos += posData[tet.z] * bary.z;
	pos += posData[tet.w] * bary.w;
	
	outPosData[vertex_id * 3 + 0] = pos.x;
	outPosData[vertex_id * 3 + 1] = pos.y;
	outPosData[vertex_id * 3 + 2] = pos.z;
}





