package csce_vis.hw2;

import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.opengl.GL12.*;
import static org.lwjgl.opengl.GL13.*;
import static org.lwjgl.opengl.GL14.*;
import static org.lwjgl.opengl.GL15.*;
import static org.lwjgl.opengl.GL20.*;
import static org.lwjgl.opengl.GL21.*;
import static org.lwjgl.opengl.GL30.*;
import static org.lwjgl.opengl.GL31.*;
import static org.lwjgl.opengl.GL32.*;
import static org.lwjgl.opengl.GL33.*;
import static org.lwjgl.opengl.GL40.*;
import static org.lwjgl.opengl.GL41.*;
import static org.lwjgl.opengl.GL42.*;
import static org.lwjgl.opengl.GL43.*;
import static org.lwjgl.opengl.GL44.*;
import static org.lwjgl.opengl.GL45.*;
import static org.lwjgl.opengl.GL46.*;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collections;
import java.util.PriorityQueue;
import java.util.Queue;

import org.lwjgl.glfw.GLFW;

import lwjglengine.graphics.Cubemap;
import lwjglengine.graphics.Framebuffer;
import lwjglengine.graphics.Material;
import lwjglengine.graphics.Shader;
import lwjglengine.graphics.ShaderStorageBuffer;
import lwjglengine.graphics.Texture;
import lwjglengine.main.Main;
import lwjglengine.model.Model;
import lwjglengine.model.ModelInstance;
import lwjglengine.model.ModelTransform;
import lwjglengine.model.VertexArray;
import lwjglengine.player.Camera;
import lwjglengine.player.PlayerInputController;
import lwjglengine.scene.DirLight;
import lwjglengine.scene.Light;
import lwjglengine.scene.PointLight;
import lwjglengine.scene.Scene;
import lwjglengine.screen.PerspectiveScreen;
import lwjglengine.screen.ScreenQuad;
import lwjglengine.screen.UIScreen;
import lwjglengine.ui.Text;
import lwjglengine.ui.UIElement;
import lwjglengine.util.BufferUtils;
import lwjglengine.util.ShaderUtils;
import lwjglengine.window.Window;
import myutils.file.FileUtils;
import myutils.math.Mat4;
import myutils.math.MathUtils;
import myutils.math.Vec3;
import myutils.misc.Pair;
import myutils.noise.base.PerlinNoise;
import raytracing.bvh.BVH;
import raytracing.bvh.BVHManager;

public class HW2Window extends Window {

	//i give up. Just going to showcase large number. Large number is nice

	//TODO
	// - ok, seems like we hit a bottleneck on rendering at around 8 million particles. 
	//   - ideas for speeding up rendering?
	// - correctly render particles
	//   - currently, im doing very jank thing of just calling glRenderArrays without having an array bound
	//   - perhaps rendering will be faster with a vao / vbo?

	// - LIDAR!!!!
	//   - every time we press 'e' or something, sweep up and put in particles where the ray collides
	//   - also allow to throw grenades that emit 'sound waves' so we can see them bouncing off of the environment
	//     - can say that the particles generated by the grenades satisfy the 'bouncing' requirement, as well as
	//       the random generation requirement (second one is a stretch). 
	//     - sound particles are green
	//   - render normal lidar particles on gradient. 
	//     - closer is yellow/orange, farther is blue
	//   - make one light source where player spawns, and rest of map dark
	//     - want to be able to see particles through walls though, how to do that?
	//   - implement player movement physics
	//   - add monster in the dark somewhere
	//     - probably entrance to B site through upper tuns is best. Easiest to get up close
	//     - monster should be red
	//     - window should auto close after monster is onscreen for a second or so
	//     - chromatic abberation or some other effect could be fun
	//     - make monster 'charge' at you by assigning them some initial velocity
	//   - maybe have a 'lidar gun', and can also draw lines from the gun to where the points are projected

	// - presentation checklist:
	//   - first keep the lights on and satisfy minimum requirements:
	//     - particles bouncing off of environment
	//     - triangular particle generator
	//     - explosion?
	//     - mention how many particles can handle, using GPU to update etc.
	//     - make sure to mention how many triangles there are in environment, and how we're using BVH to speed up 
	//       particle vs. environment collisions, and how the BVH is serialized to be put on the GPU
	//   - turn off lights and introduce extra stuff
	//     - show off lidar
	//     - show off sound bubble
	//     - make your way to B tuns

	//extras:
	// - allow for pre-processed point light shadow cubemaps for faster rendering. 

	//maximum amount of particles possible within buffer
	private static final int MAX_PARTICLE_CNT = (1 << 20);

	//how many particles we'll read from the buffer to try to generate new ones
	//should be a divisor of MAX_PARTICLE_CNT
	private static final int GEN_BATCH_SIZE = (1 << 12);

	//how many batches we'll pull out of the particle buffer before giving up on generating particles
	//per update
	private static final int GEN_MAX_TRIES = (1 << 4);

	//need to use all dimensions, as enforced dimension size is 65536 or 2^16
	private static final int COMPUTE_X_DIM = (1 << 16);
	private static final int COMPUTE_Y_DIM = MAX_PARTICLE_CNT / COMPUTE_X_DIM;

	private long genBytePtr = 0;
	private Queue<Particle> genList;

	private ShaderStorageBuffer posbo; //{x, y, z, lifespan}
	private ShaderStorageBuffer velbo; //{vx, vy, vz, air friction coeff}
	private ShaderStorageBuffer huebo; //{r, g, b, is_static}
	private ShaderStorageBuffer attrbo; //{proximity hue, restitution, -1, -1}

	private Shader particleUpdateShader, particleRenderShader;

	private PlayerInputController pic;

	private Framebuffer renderBuffer = null;
	private Texture renderColorMap;

	private final int WORLD_SCENE = Scene.generateScene();

	private BVHManager bvh;
	private Model dust2, scp173;

	private PerspectiveScreen perspectiveScreen;

	private boolean lightsOn = true;

	private boolean mousePressed = false;

	private PriorityQueue<Long> activeParticles = new PriorityQueue<>();

	private UIScreen uiScreen;
	private final int UI_SCENE = Scene.generateScene();
	private Text particleCountText;

	public HW2Window(int xOffset, int yOffset, int width, int height, Window parentWindow) {
		super(xOffset, yOffset, width, height, parentWindow);
		this.init();
	}

	private void init() {
		this.setLockCursorOnSelect(true);
		this.setDeselectOnEscPressed(true);
		this.setUnlockCursorOnEscPressed(true);

		this.uiScreen = new UIScreen();
		this.particleCountText = new Text(10, 10, " ", UI_SCENE);
		this.particleCountText.setFrameAlignmentStyle(UIElement.FROM_LEFT, UIElement.FROM_TOP);
		this.particleCountText.setContentAlignmentStyle(UIElement.ALIGN_LEFT, UIElement.ALIGN_TOP);
		this.particleCountText.bind(this.rootUIElement);

		this.genList = new ArrayDeque<>();

		this.pic = new PlayerInputController(new Vec3(-21.08027f, 1.7262033f, 10.618463f));
		this.pic.setNoclipSpeed(0.125f);
		this.pic.setCollisionScene(WORLD_SCENE);
		this.pic.setAcceptPlayerInputs(false);
		this.pic.setDoNoclip(false);

		this.particleUpdateShader = ShaderUtils.createShader("/csce_vis/hw2/particle_update.compute", GL_COMPUTE_SHADER);
		this.particleRenderShader = ShaderUtils.createShader("/csce_vis/hw2/particle.vert", "/csce_vis/hw2/particle.frag");
		this.particleRenderShader.setUniform1i("geometry_pos_tex", 0);

		this.perspectiveScreen = new PerspectiveScreen();
		this.perspectiveScreen.setWorldCameraFOV(90f);
		this.perspectiveScreen.setWorldScene(WORLD_SCENE);
		this.perspectiveScreen.renderSkybox(true);
		this.perspectiveScreen.renderDecals(false);
		this.perspectiveScreen.renderPlayermodel(false);
		this.perspectiveScreen.renderParticles(false);

		BufferedImage[] skyboxSides = new BufferedImage[6];
		String skyboxDir = "/res/skybox/lake/";
		for (int i = 0; i < 6; i++) {
			skyboxSides[i] = FileUtils.loadImageRelative(skyboxDir + Cubemap.CUBEMAP_SIDE_NAMES[i] + ".jpg");
		}
		Cubemap skybox = new Cubemap(skyboxSides);
		Scene.skyboxes.put(WORLD_SCENE, skybox);

		Light light = new DirLight(new Vec3(1, -1, 1), new Vec3(1), 0.25f);
		Light.addLight(WORLD_SCENE, light);

		//		double[][] pl_pos = { { -133.77034, 10.095735, -78.82737 }, { -72.976555, 9.804072, -73.017395 }, { -63.116432, -1.0782955, -102.84278 }, { 21.840126, -2.7906053, -169.90938 }, { 87.011604, -5.049504, -9.689175 }, { 35.254993, 5.876994, -34.506153 }, };
		//		for (double[] d : pl_pos) {
		//			Light pl = new PointLight(new Vec3(d[0], d[1], d[2]), new Vec3(1), 0.1f, 1.0f, 0.045f, 0.0075f);
		//			Light.addLight(WORLD_SCENE, pl);
		//		}

		//initialize bvh
		this.bvh = new BVHManager();

		try {
			this.dust2 = Model.loadModelFileRelative("/res/dust2/dust2_blend.obj");

			Mat4 transform = Mat4.identity();
			transform.muli(Mat4.rotateX((float) Math.toRadians(90f)));
			transform.muli(Mat4.scale(0.05f));

			ModelInstance dust2_inst = new ModelInstance(this.dust2, WORLD_SCENE);
			dust2_inst.setModelTransform(new ModelTransform(transform));

			Model.activateCollisionMesh(dust2_inst.getID());

			this.addModelInstanceToBVH(dust2_inst);
		}
		catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		//		try {
		//			this.scp173 = Model.loadModelFileRelative("/res/scp173/scp173.obj");
		//
		//			Mat4 transform = Mat4.identity();
		//			transform.muli(Mat4.scale(0.8f));
		//			transform.muli(Mat4.translate(new Vec3(-26.721302f, 0.4315538f, -23.567879f)));
		//
		//			ModelInstance scp_inst = new ModelInstance(this.scp173, WORLD_SCENE);
		//			scp_inst.setModelTransform(new ModelTransform(transform));
		//			scp_inst.setMaterial(new Material(new Vec3(1, 0, 0)));
		//
		//			this.addModelInstanceToBVH(scp_inst);
		//		}
		//		catch (IOException e) {
		//			// TODO Auto-generated catch block
		//			e.printStackTrace();
		//		}

		//		{
		//			Model suzanne = Model.loadModelFile(FileUtils.loadFileRelative("/res/suzanne/suzanne.obj"));
		//
		//			Mat4 transform = Mat4.identity();
		//			transform.muli(Mat4.scale(30));
		//			transform.muli(Mat4.rotateX((float) Math.toRadians(30)));
		//			transform.muli(Mat4.translate(new Vec3(0, -20, 0)));
		//
		//			ModelInstance inst = new ModelInstance(suzanne, transform, WORLD_SCENE);
		//			this.addModelInstanceToBVH(inst);
		//		}

		this.bvh.build();

		//set up particle array buffers. need to keep track of:
		// - position
		// - velocity
		// - hue
		// - attr (misc data)
		this.posbo = new ShaderStorageBuffer(MAX_PARTICLE_CNT * 4 * 4);
		this.posbo.setUsage(GL_DYNAMIC_DRAW);

		this.velbo = new ShaderStorageBuffer(MAX_PARTICLE_CNT * 4 * 4);
		this.velbo.setUsage(GL_DYNAMIC_DRAW);

		this.huebo = new ShaderStorageBuffer(MAX_PARTICLE_CNT * 4 * 4);
		this.huebo.setUsage(GL_DYNAMIC_DRAW);

		this.attrbo = new ShaderStorageBuffer(MAX_PARTICLE_CNT * 4 * 4);
		this.attrbo.setUsage(GL_DYNAMIC_DRAW);

		this.resetParticles();

		this._resize();
	}

	private void addModelInstanceToBVH(ModelInstance inst) {
		Model model = inst.getModel();
		Mat4 transform = inst.getModelTransform().getModelMatrix();
		Material material = inst.getMaterial();

		ArrayList<VertexArray> meshes = model.getMeshes();
		for (VertexArray v : meshes) {
			int[] indices = v.getIndices();
			Vec3[] vertices = new Vec3[v.getVertices().length / 3];
			for (int i = 0; i < vertices.length; i++) {
				float x = v.getVertices()[i * 3 + 0];
				float y = v.getVertices()[i * 3 + 1];
				float z = v.getVertices()[i * 3 + 2];
				vertices[i] = new Vec3(x, y, z);
			}
			for (int i = 0; i < indices.length / 3; i++) {
				Vec3 a = vertices[indices[i * 3 + 0]];
				Vec3 b = vertices[indices[i * 3 + 1]];
				Vec3 c = vertices[indices[i * 3 + 2]];

				//apply model transform
				a = transform.mul(a, 1);
				b = transform.mul(b, 1);
				c = transform.mul(c, 1);
				this.bvh.addTriangle(a, b, c, material);
			}
		}
	}

	@Override
	protected void _kill() {
		this.uiScreen.kill();
		Scene.removeScene(UI_SCENE);

		this.posbo.kill();
		this.velbo.kill();
		this.huebo.kill();
		this.attrbo.kill();

		this.particleUpdateShader.kill();
		this.particleRenderShader.kill();

		this.renderBuffer.kill();

		this.bvh.kill();
		this.dust2.kill();

		Scene.removeScene(WORLD_SCENE);
	}

	@Override
	protected void _resize() {
		if (this.renderBuffer != null) {
			this.renderBuffer.kill();
			this.renderBuffer = null;
		}

		if (this.getWidth() > 0 && this.getHeight() > 0) {
			this.renderBuffer = new Framebuffer(this.getWidth(), this.getHeight());
			this.renderColorMap = new Texture(this.getWidth(), this.getHeight(), GL_RGBA32F, GL_RGBA, GL_FLOAT);
			this.renderBuffer.bindTextureToBuffer(GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, this.renderColorMap.getID());
			this.renderBuffer.addDepthBuffer();
			this.renderBuffer.setDrawBuffers(new int[] { GL_COLOR_ATTACHMENT0 });
			this.renderBuffer.isComplete();
		}

		this.perspectiveScreen.setScreenDimensions(this.getWidth(), this.getHeight());
		this.uiScreen.setScreenDimensions(this.getWidth(), this.getHeight());
	}

	@Override
	public String getDefaultTitle() {
		return "Homework 2";
	}

	//just kill all particles
	private void resetParticles() {
		float[] pos_data = new float[MAX_PARTICLE_CNT * 4];
		for (int i = 0; i < MAX_PARTICLE_CNT; i++) {
			pos_data[i * 4 + 3] = -1; //set lifespan
		}
		this.posbo.setData(pos_data);

		this.activeParticles.clear();
	}

	//tries to generate whatever is inside genList
	//if it runs out of tries, then try to generate on next update
	private void _generateParticles() {
		for (int i = 0; i < GEN_MAX_TRIES && this.genList.size() != 0; i++) {
			float[] pos_data = new float[GEN_BATCH_SIZE * 4];
			float[] vel_data = new float[GEN_BATCH_SIZE * 4];
			float[] hue_data = new float[GEN_BATCH_SIZE * 4];
			float[] attr_data = new float[GEN_BATCH_SIZE * 4];

			this.posbo.getSubData(pos_data, this.genBytePtr);
			this.velbo.getSubData(vel_data, this.genBytePtr);
			this.huebo.getSubData(hue_data, this.genBytePtr);
			this.attrbo.getSubData(attr_data, this.genBytePtr);

			for (int j = 0; j < GEN_BATCH_SIZE && this.genList.size() != 0; j++) {
				if (pos_data[j * 4 + 3] > 0) {
					//still alive
					continue;
				}

				//put particle here
				Particle p = this.genList.poll();
				pos_data[j * 4 + 0] = p.pos.x;
				pos_data[j * 4 + 1] = p.pos.y;
				pos_data[j * 4 + 2] = p.pos.z;
				pos_data[j * 4 + 3] = p.lifespan;

				vel_data[j * 4 + 0] = p.vel.x;
				vel_data[j * 4 + 1] = p.vel.y;
				vel_data[j * 4 + 2] = p.vel.z;
				vel_data[j * 4 + 3] = p.air_friction_coeff;

				hue_data[j * 4 + 0] = p.hue.x;
				hue_data[j * 4 + 1] = p.hue.y;
				hue_data[j * 4 + 2] = p.hue.z;
				hue_data[j * 4 + 3] = p.is_static ? 1 : -1;

				attr_data[j * 4 + 0] = p.proximity_hue ? 1 : -1;
				attr_data[j * 4 + 1] = p.coeff_restitution;

				this.activeParticles.add(System.currentTimeMillis() + (int) (p.lifespan * 1000));
			}

			this.posbo.setSubData(pos_data, this.genBytePtr);
			this.velbo.setSubData(vel_data, this.genBytePtr);
			this.huebo.setSubData(hue_data, this.genBytePtr);
			this.attrbo.setSubData(attr_data, this.genBytePtr);

			this.genBytePtr = (this.genBytePtr + GEN_BATCH_SIZE * 4 * 4) % (MAX_PARTICLE_CNT * 4 * 4);
		}
	}

	private void generateParticle(Particle p) {
		this.genList.add(p);
	}

	@Override
	protected void _update() {
		this.pic.update();

		if (this.mousePressed) {
			for (int i = 0; i < (1 << 10); i++) {
				Vec3 pos = new Vec3(this.pic.getTop());
				Vec3 vel = new Vec3(this.pic.getFacing());
				vel.muli(MathUtils.random(8, 8.5f));
				float deviation = 0.4f * (float) Math.random();
				vel.addi(MathUtils.generateRandomPerpendicularVec3(vel).mul(deviation));
				Particle p = new Particle(pos, vel);
				p.lifespan = MathUtils.random(8, 12);
				p.coeff_restitution = MathUtils.random(0.8f, 1);
				this.generateParticle(p);
			}
		}

		//generate particles
		this._generateParticles();

		while (this.activeParticles.size() != 0 && this.activeParticles.peek() < System.currentTimeMillis()) {
			this.activeParticles.poll();
		}
		this.particleCountText.setText(this.activeParticles.size() + "");
		this.particleCountText.setWidth(this.particleCountText.getTextWidth());

		//update particles
		{
			this.particleUpdateShader.enable();
			this.particleUpdateShader.setUniform1i("compute_x_dim", COMPUTE_X_DIM);
			this.particleUpdateShader.setUniform1i("compute_y_dim", COMPUTE_Y_DIM);
			this.particleUpdateShader.setUniform1f("dt", Main.getDeltaSeconds());

			this.posbo.bindToBase(1);
			this.velbo.bindToBase(2);
			this.huebo.bindToBase(3);
			this.attrbo.bindToBase(4);

			this.bvh.getBVHSSBO().bindToBase(5);
			this.bvh.getBoundingBoxSSBO().bindToBase(6);
			this.bvh.getPrimitiveSSBO().bindToBase(7);

			glDispatchCompute(COMPUTE_X_DIM, COMPUTE_Y_DIM, 1);
		}
	}

	@Override
	protected void renderContent(Framebuffer outputBuffer) {
		Camera camera = new Camera((float) Math.toRadians(90), this.getWidth(), this.getHeight(), 0.1f, 400);
		camera.setPos(this.pic.getTop());
		camera.setFacing(this.pic.getFacing());
		Mat4 pr_matrix = camera.getProjectionMatrix();
		Mat4 vw_matrix = camera.getViewMatrix();

		this.perspectiveScreen.setCamera(camera);

		//render geometry
		if (this.lightsOn) {
			this.perspectiveScreen.render(outputBuffer);
		}

		//render particles
		{
			this.particleRenderShader.enable();
			this.particleRenderShader.setUniformMat4("pr_matrix", pr_matrix);
			this.particleRenderShader.setUniformMat4("vw_matrix", vw_matrix);
			this.particleRenderShader.setUniform3f("view_pos", this.pic.getTop());
			this.particleRenderShader.setUniform1i("do_gdt", this.lightsOn ? 1 : 0);

			this.perspectiveScreen.geometryPositionMap.bind(GL_TEXTURE0);

			this.posbo.bindToBase(1);
			this.velbo.bindToBase(2);
			this.huebo.bindToBase(3);
			this.attrbo.bindToBase(4);

			this.renderBuffer.bind();
			glClearDepth(1); // maximum value
			glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

			glEnable(GL_DEPTH_TEST);
			glDepthFunc(GL_LESS);

			//			glEnable(GL_POINT_SMOOTH);
			//			glEnable(GL_BLEND);
			//			glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

			//			glPointSize(2f);
			glEnable(GL_PROGRAM_POINT_SIZE);
			glViewport(0, 0, this.getWidth(), this.getHeight());
			glDrawArrays(GL_POINTS, 0, MAX_PARTICLE_CNT);
		}

		//render back to output buffer
		{
			outputBuffer.bind();
			Shader.SPLASH.enable();
			Shader.SPLASH.setUniform1f("alpha", 1f);
			this.renderColorMap.bind(GL_TEXTURE0);
			ScreenQuad.screenQuad.render();
		}

		this.uiScreen.setUIScene(UI_SCENE);
		this.uiScreen.render(outputBuffer);
	}

	@Override
	protected void renderOverlay(Framebuffer outputBuffer) {
		// TODO Auto-generated method stub

	}

	@Override
	protected void selected() {
		this.pic.setAcceptPlayerInputs(true);
	}

	@Override
	protected void deselected() {
		this.pic.setAcceptPlayerInputs(false);
	}

	@Override
	protected void subtreeSelected() {
		// TODO Auto-generated method stub

	}

	@Override
	protected void subtreeDeselected() {
		// TODO Auto-generated method stub

	}

	@Override
	protected void _mousePressed(int button) {
		this.mousePressed = true;
	}

	@Override
	protected void _mouseReleased(int button) {
		this.mousePressed = false;
	}

	@Override
	protected void _mouseScrolled(float wheelOffset, float smoothOffset) {
		// TODO Auto-generated method stub

	}

	private ArrayList<Vec3> pos_list = new ArrayList<>();

	@Override
	protected void _keyPressed(int key) {
		switch (key) {
		case GLFW.GLFW_KEY_Q:
			this.resetParticles();
			break;

		//lidar scanner
		case GLFW.GLFW_KEY_E: {
			float rand_coeff = 0.01f;
			Mat4 inv_camera = this.perspectiveScreen.getCamera().getInvViewMatrix();
			float vertical_fov = (float) Math.toRadians(90f);

			float dist = 5f;
			float ymax = dist * (float) Math.tan(vertical_fov / 2.0);
			float aspect_ratio = (float) this.getWidth() / (float) this.getHeight();
			float xmax = ymax * aspect_ratio;

			int y_cnt = 100;
			int x_cnt = (int) (y_cnt * aspect_ratio);

			float y_inc = (2.0f * ymax) / y_cnt;
			float x_inc = (2.0f * xmax) / x_cnt;

			float y_ptr = -ymax + y_inc / 2;
			for (int i = 0; i < y_cnt; i++, y_ptr += y_inc) {
				float x_ptr = -xmax + x_inc / 2;
				for (int j = 0; j < x_cnt; j++, x_ptr += x_inc) {
					float rx = rand_coeff * MathUtils.random(-1, 1);
					float ry = rand_coeff * MathUtils.random(-1, 1);

					Vec3 dir = new Vec3(x_ptr + rx, y_ptr + ry, -dist);
					dir.normalize();
					dir = inv_camera.mul(dir, 0);
					Vec3 camera_pos = this.perspectiveScreen.getCamera().getPos();

					Pair<Vec3, Material> ecoll = this.bvh.rayCollision(camera_pos, dir);
					if (ecoll == null) {
						continue;
					}

					Vec3 coll_pt = ecoll.first;
					//					coll_pt.subi(dir.mul(0.1f));
					Particle p = new Particle(coll_pt);
					p.hue = ecoll.second.getDiffuse().xyz();

					if (p.hue.y != 0) {
						p.proximity_hue = true;
					}

					this.generateParticle(p);
				}
			}
			break;
		}

		//'sound' grenade
		case GLFW.GLFW_KEY_G: {
			Vec3 color = new Vec3(57, 173, 72).mul(1.0f / 255.0f);

			Vec3 center = this.pic.getTop().add(this.pic.getFacing().mul(1));

			for (int i = 0; i < 30000; i++) {
				Vec3 dir = MathUtils.randomUnitDir();
				float vel = 6f;

				Particle p = new Particle(center, dir.mul(vel));
				p.lifespan = MathUtils.random(2, 5);
				p.air_friction_coeff = 0;
				p.hue = new Vec3(color);
				this.generateParticle(p);
			}
			break;
		}

		case GLFW.GLFW_KEY_P:
			pos_list.add(new Vec3(this.pic.getPos()));
			break;

		case GLFW.GLFW_KEY_O:
			for (Vec3 v : pos_list) {
				System.out.println(v);
			}
			break;

		case GLFW.GLFW_KEY_L:
			this.lightsOn = !this.lightsOn;
			break;

		case GLFW.GLFW_KEY_C:
			this.pic.setDoNoclip(false);
			break;

		case GLFW.GLFW_KEY_R:
			this.resetParticles();
			break;
		}
	}

	@Override
	protected void _keyReleased(int key) {
		// TODO Auto-generated method stub

	}

	class Particle {
		Vec3 pos, vel, hue;
		float lifespan, air_friction_coeff, coeff_restitution;
		boolean is_static, proximity_hue;

		public Particle(Vec3 _pos) {
			this(_pos, new Vec3(0));
			this.is_static = true;
		}

		public Particle(Vec3 _pos, Vec3 _vel) {
			this(_pos, _vel, new Vec3(1), 120, 0);
		}

		public Particle(Vec3 _pos, Vec3 _vel, Vec3 _hue, float _lifespan, float _air_friction_coeff) {
			this.pos = new Vec3(_pos);
			this.vel = new Vec3(_vel);
			this.hue = new Vec3(_hue);
			this.lifespan = _lifespan;
			this.air_friction_coeff = _air_friction_coeff;
			this.is_static = false;
			this.coeff_restitution = 1;
		}
	}

}
