#version 430 core
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D dispX_dx_Texture;
layout(rgba32f, binding = 1) uniform image2D dispY_dx_Texture;
layout(rgba32f, binding = 2) uniform image2D dispZ_dx_Texture;

layout(rgba32f, binding = 3) uniform image2D dispX_dz_Texture;
layout(rgba32f, binding = 4) uniform image2D dispY_dz_Texture;
layout(rgba32f, binding = 5) uniform image2D dispZ_dz_Texture;

layout(rgba32f, binding = 6) uniform image2D normalTexture;

void main() {
	ivec2 tex_coord = ivec2(int(gl_GlobalInvocationID.x), int(gl_GlobalInvocationID.y));
	float xdx = imageLoad(dispX_dx_Texture, tex_coord).r;
	float ydx = imageLoad(dispY_dx_Texture, tex_coord).r;
	float zdx = imageLoad(dispZ_dx_Texture, tex_coord).r;
	float xdz = imageLoad(dispX_dz_Texture, tex_coord).r;
	float ydz = imageLoad(dispY_dz_Texture, tex_coord).r;
	float zdz = imageLoad(dispZ_dz_Texture, tex_coord).r;
	vec3 normal = normalize(cross(vec3(xdz, ydz, zdz), vec3(xdx, ydx, zdx)));
	normal = (normal * 0.5) + 0.5;
	imageStore(normalTexture, tex_coord, vec4(normal, 1));
}