#version 430 core
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D dispX_Texture;
layout(rgba32f, binding = 1) uniform image2D dispY_Texture;
layout(rgba32f, binding = 2) uniform image2D dispZ_Texture;

layout(rgba32f, binding = 3) uniform image2D dispTexture;

void main() {
	ivec2 tex_coord = ivec2(int(gl_GlobalInvocationID.x), int(gl_GlobalInvocationID.y));
	float x = imageLoad(dispX_Texture, tex_coord).r;
	float y = imageLoad(dispY_Texture, tex_coord).r;
	float z = imageLoad(dispZ_Texture, tex_coord).r;
	imageStore(dispTexture, tex_coord, vec4(x, y, z, 1));
}