#version 430 core
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D evolvedSpectraTexture;
layout(rgba32f, binding = 1) uniform image2D waveInfoTexture;

layout(rgba32f, binding = 2) uniform image2D dispX_dx_Texture;
layout(rgba32f, binding = 3) uniform image2D dispY_dx_Texture;
layout(rgba32f, binding = 4) uniform image2D dispZ_dx_Texture;

layout(rgba32f, binding = 5) uniform image2D dispX_dz_Texture;
layout(rgba32f, binding = 6) uniform image2D dispY_dz_Texture;
layout(rgba32f, binding = 7) uniform image2D dispZ_dz_Texture;

vec2 complex_mult(vec2 a, vec2 b) {
	return vec2(a.x * b.x - a.y * b.y, a.x * b.y + a.y * b.x);
}

void main() {
	ivec2 tex_coord = ivec2(int(gl_GlobalInvocationID.x), int(gl_GlobalInvocationID.y));
	
	vec4 info = imageLoad(waveInfoTexture, tex_coord);

	vec2 ht = imageLoad(evolvedSpectraTexture, tex_coord).xy;
	vec2 iht = vec2(-ht.y, ht.x);
	
	vec2 dispx_dx = -ht * info.x * info.x * info.y;
	vec2 dispy_dx = iht * info.x;
	vec2 dispz_dx = -ht * info.x * info.z * info.y;
	
	vec2 dispx_dz = -ht * info.z * info.x * info.y;
	vec2 dispy_dz = iht * info.z;
	vec2 dispz_dz = -ht * info.z * info.z * info.y;
	
	imageStore(dispX_dx_Texture, tex_coord, vec4(dispx_dx, 0, 1));
	imageStore(dispY_dx_Texture, tex_coord, vec4(dispy_dx, 0, 1));
	imageStore(dispZ_dx_Texture, tex_coord, vec4(dispz_dx, 0, 1));
	
	imageStore(dispX_dz_Texture, tex_coord, vec4(dispx_dz, 0, 1));
	imageStore(dispY_dz_Texture, tex_coord, vec4(dispy_dz, 0, 1));
	imageStore(dispZ_dz_Texture, tex_coord, vec4(dispz_dz, 0, 1));
}