#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D out_height;
layout(rgba32f, binding = 1) uniform image2D out_normal;

void main() {
    for (int x = 0; x < 256; ++x) {
        for (int z = 0; z < 256; ++z) {
            imageStore(out_height, ivec2(x, z), vec4(vec3(0, 1, 0), 1));
            imageStore(out_normal, ivec2(x, z), vec4(vec3(0, 1, 0), 1));
        }
    }
}


