#version 430 core
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D spectraTexture;
layout(rgba32f, binding = 1) uniform image2D noiseTexture;
layout(rgba32f, binding = 2) uniform image2D waveInfoTexture;

uniform int spectra_sz;

const float g = 9.81;
const float pi = 3.14159265;
const float sigma = 0.074;	//surface tension coeff
const float rho = 1000.0;	//density of water
const float length_scale = 16;

uniform vec2 wind_dir;
uniform float h;	//height of water in meters
uniform float U;	//avg wind speed (m/s)
uniform float F;	//fetch, length of area over which wind is acting on water
uniform float omega_p;	//peak energy frequency
uniform float multiplier;	//for debugging

float jonswap(float omega) {
	float gamma = 3.3;	
	float r = exp(-pow(omega - omega_p, 2.0) / (2.0 * sigma * sigma * omega_p * omega_p));
	float alpha = 0.076 * pow(U * U / (F * g), 0.22);
	float beta = 5.0 / 4.0;
	float ans = (alpha * g * g) / pow(omega, 5.0);
	ans *= exp(-beta * pow(omega_p / omega, 4.0));
	ans *= pow(gamma, r);
	return ans;
}

float dispersion(float k) {
	return sqrt((g * k + (sigma / rho) * pow(k, 3.0)) * tanh(k * h));
}

float sech(float x) {
	return 1.0 / cosh(x);
}

float dispersion_derivative(float k) {
	float numer = h * (g * k + (sigma / rho) * pow(k, 3.0)) * pow(sech(k * h), 2.0) + pow(dispersion(k), 2.0);
	float denom = 2.0 * dispersion(k);
	return numer / denom;
}

float cos2_spread(vec2 k) {
	float c = dot(normalize(k), wind_dir);
	if(c <= 0) return 0;
	return 2.0 / pi * c * c;
}

void main() {
	ivec2 tex_coord = ivec2(int(gl_GlobalInvocationID.x), int(gl_GlobalInvocationID.y));
	
	float delta_k = 2.0 * pi / length_scale;
	vec2 k = vec2(tex_coord.x, tex_coord.y);
	k -= spectra_sz / 2.0 - 0.5;
	k *= delta_k;
	float wavenumber = length(k);
	float theta = atan(k.y, k.x);
	float omega = dispersion(wavenumber);
	float domega_dk = dispersion_derivative(wavenumber);
	
	float energy = jonswap(omega);
	float spread = cos2_spread(k);
	
	float s = sqrt(2.0 * energy * spread * domega_dk / wavenumber * delta_k * delta_k);
	s *= multiplier;
	vec4 ret = vec4(0, 0, 0, 1);
	ret.x = s * imageLoad(noiseTexture, tex_coord).x;
	ret.y = s * imageLoad(noiseTexture, tex_coord).y;
	imageStore(spectraTexture, tex_coord, ret);
	
	imageStore(waveInfoTexture, tex_coord, vec4(k.x, 1.0 / wavenumber, k.y, omega));
}