#version 430 core
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D spectraTexture;
layout(rgba32f, binding = 1) uniform image2D noiseTexture;

uniform int spectra_sz;

const vec2 wind_dir = vec2(1, 0);
const float g = 9.81;
const float h = 200;	//height of water in meters
const float pi = 3.14159265;
const float sigma = 0.074;	//surface tension coeff
const float rho = 1000.0;	//density of water

float jonswap(float omega) {
	float U = 25.0;	//avg wind speed (m/s)
	float F = 250.0;	//fetch, length of area over which wind is acting on water
	float omega_p = 22.0 * (g * g / (U * F));
	float gamma = 3.3;	
	float r = exp(-pow(omega - omega_p, 2.0) / (2.0 * sigma * sigma * omega_p * omega_p));
	float alpha = 0.076 * pow(U * U / (F * g), 0.22);
	float beta = 5.0 / 4.0;
	float ans = (alpha * g * g) / pow(omega, 5.0);
	ans *= exp(-beta * pow(omega_p / omega, 4.0));
	ans *= pow(gamma, r);
	return ans;
}

float dispersion(float k) {
	return sqrt((g * k + (sigma / rho) * pow(k, 3.0)) * tanh(k * h));
}

float sech(float x) {
	return 1.0 / cosh(x);
}

float dispersion_derivative(float k) {
	float numer = h * (g * k + (sigma / rho) * pow(k, 3.0)) * pow(sech(k * h), 2.0) + pow(dispersion(k), 2.0);
	float denom = 2.0 * dispersion(k);
	return numer / denom;
}

float cos2_spread(vec2 k) {
	float c = dot(normalize(k), wind_dir);
	if(c <= 0) return 0;
	return 2.0 / pi * c * c;
}

void main() {
	ivec2 tex_coord = ivec2(int(gl_GlobalInvocationID.x), int(gl_GlobalInvocationID.y));
	
	vec2 k = vec2(tex_coord.x, tex_coord.y);
	k -= spectra_sz / 2.0 - 0.5;
	float theta = atan(k.y, k.x);
	float wavenumber = length(k) / spectra_sz;
	float omega = dispersion(wavenumber);
	
	float s = sqrt(2.0 * jonswap(omega) * cos2_spread(k) * dispersion_derivative(wavenumber) / wavenumber / spectra_sz);
	vec4 ret = vec4(0, 0, 0, 1);
	ret.x = s * imageLoad(noiseTexture, tex_coord).x;
	ret.y = s * imageLoad(noiseTexture, tex_coord).y;
	imageStore(spectraTexture, tex_coord, ret);
}