#version 430 core
layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2D Dx_Dz;
layout(rgba32f, binding = 1) uniform image2D Dy_Dxz;
layout(rgba32f, binding = 2) uniform image2D Dyx_Dyz;
layout(rgba32f, binding = 3) uniform image2D Dxx_Dzz;

layout(rgba32f, binding = 4) uniform image2D dispTexture;
layout(rgba32f, binding = 5) uniform image2D derivativeTexture;

uniform float lambda;

uniform float dt;
uniform float foam_bias;
uniform float foam_generation_rate;
uniform float foam_decay_rate;

uniform float length_scale;
uniform float cascade_scale;

void main() {
	ivec2 tex_coord = ivec2(int(gl_GlobalInvocationID.x), int(gl_GlobalInvocationID.y));
	
	vec2 DxDz = imageLoad(Dx_Dz, tex_coord).xy;
	vec2 DyDxz = imageLoad(Dy_Dxz, tex_coord).xy;
	vec2 DyxDyz = imageLoad(Dyx_Dyz, tex_coord).xy;
	vec2 DxxDzz = imageLoad(Dxx_Dzz, tex_coord).xy;
	
	vec3 disp = vec3(DxDz.x * lambda, DyDxz.x, DxDz.y * lambda);
	vec4 derivative = vec4(DyxDyz, DxxDzz * lambda);
	
	float old_foam = imageLoad(dispTexture, tex_coord).w;
	float foam = old_foam * exp(-foam_decay_rate);
	float Jxx = 1.0 + lambda * DxxDzz.x * cascade_scale * length_scale;
	float Jzz = 1.0 + lambda * DxxDzz.y * cascade_scale * length_scale;
	float Jxz = lambda * DyDxz.y * cascade_scale * length_scale;
	float jacobian = Jxx * Jzz - Jxz * Jxz;
	jacobian = (jacobian - foam_bias);
	if(jacobian > 0) foam += foam_generation_rate * jacobian;
	
	imageStore(dispTexture, tex_coord, vec4(disp, foam));
	imageStore(derivativeTexture, tex_coord, derivative);
}