#version 430 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

struct Particle {
	vec3 pos;
	vec3 vel;
	int hash;
};

layout(binding = 0) buffer particleBuffer {
	Particle[] particleData;
};

layout(binding = 1) buffer hashLUTBuffer {
	int[] hashLUT;
};

struct ParticleInfo {
	vec3 pred_pos;
	float density;
	vec3 visc_force;
	float near_density;
};	

layout(binding = 2) buffer particleInfoBuffer {
	ParticleInfo[] particleInfoData;
};

uniform float dt;
uniform vec3 gravity;
uniform int nr_particles;

uniform vec3 bounds_min;
uniform vec3 bounds_max;

uniform float smoothing_radius;
uniform int hash_mod;
uniform int LUT_P1;
uniform int LUT_P2;
uniform int LUT_P3;
uniform int LUT_P4;
uniform int LUT_P5;
uniform int LUT_P6;
uniform int LUT_P7;

uniform float density_smoothing_kernel_volume;
uniform float near_density_smoothing_kernel_volume;
uniform float viscosity_smoothing_kernel_volume;

uniform float target_density;
uniform float pressure_multiplier;
uniform float near_pressure_multiplier;

int computeHash(int x, int y, int z) {
	x += LUT_P1;
	y += LUT_P2;
	z += LUT_P3;
	return abs(x * LUT_P4 + y * LUT_P5 + z * LUT_P6 + LUT_P7) % hash_mod;
}

int computeHash(vec3 pos) {
	int hash_x = int(pos.x / (smoothing_radius * 2.0));
	int hash_y = int(pos.y / (smoothing_radius * 2.0));
	int hash_z = int(pos.z / (smoothing_radius * 2.0));
	return computeHash(hash_x, hash_y, hash_z);
}

float densitySmoothingKernelSlope(float dist) {
	return -3.0 * pow(max(0.0, smoothing_radius - dist), 2.0);
}

float nearDensitySmoothingKernelSlope(float dist) {
	return -6.0 * pow(max(0.0, smoothing_radius - dist), 5.0);
}

float densitySmoothingKernel(float dist) {
	float tmp = max(0.0, smoothing_radius - dist);
	float ans = pow(tmp, 3.0);
	ans /= density_smoothing_kernel_volume;
	return ans;
}

float nearDensitySmoothingKernel(float dist) {
	float tmp = max(0.0, smoothing_radius - dist);
	float ans = pow(tmp, 6.0);
	ans /= near_density_smoothing_kernel_volume;
	return ans;
}

vec2 calculatePressure(float density, float near_density) {
	float density_error = density - target_density;
	float pressure = density_error * pressure_multiplier;
	float near_pressure = near_density * near_pressure_multiplier;
	return vec2(pressure, near_pressure);
}

vec2 calculateSharedPressure(vec2 d1, vec2 d2) {
	vec2 p1 = calculatePressure(d1.x, d1.y);
	vec2 p2 = calculatePressure(d2.x, d2.y);
	return vec2((p1.x + p2.x) / 2.0, (p1.y + p2.y) / 2.0);
}

vec3 calculatePressureForce(int particle_id, vec3 pos, vec2 density) {
	vec3 pressure_force = vec3(0);
	int hash_x = int(pos.x / (smoothing_radius * 2.0));
	int hash_y = int(pos.y / (smoothing_radius * 2.0));
	int hash_z = int(pos.z / (smoothing_radius * 2.0));
	int dx = mod(pos.x, smoothing_radius * 2.0) < smoothing_radius? -1 : 1;
	int dy = mod(pos.y, smoothing_radius * 2.0) < smoothing_radius? -1 : 1;
	int dz = mod(pos.z, smoothing_radius * 2.0) < smoothing_radius? -1 : 1;
	for(int i = 0; i < 8; i++){
		int nx = hash_x + ((i & 1) == 0? 0 : dx);
		int ny = hash_y + ((i & 2) == 0? 0 : dy);
		int nz = hash_z + ((i & 4) == 0? 0 : dz);
		int nhash = computeHash(nx, ny, nz);
		int start_ind = hashLUT[nhash];
		for(int j = start_ind; j < nr_particles; j++){
			int chash = particleData[j].hash;
			if(chash != nhash) {
				break;
			}
			if(j == particle_id) {
				continue;
			}
			vec3 cpos = particleData[j].pos;
			vec2 cdensity = vec2(particleInfoData[j].density, particleInfoData[j].near_density);
			float dist = distance(pos, cpos);
			vec3 dir = pos - cpos;
			if(dist < 0.001) {
				dir.x = 1;
				dir.y = 0;
			}
			else {
				dir /= dist;
			}
			float density_slope = densitySmoothingKernelSlope(dist);
			float near_density_slope = nearDensitySmoothingKernelSlope(dist);
			vec2 shared_pressure = calculateSharedPressure(density, cdensity);
			pressure_force -= dir * ((shared_pressure.x * density_slope / density.x) + (shared_pressure.y * near_density_slope / density.y));
		}
	}
	return pressure_force;
}

void main() {
	int particle_id = int(gl_GlobalInvocationID.x);
	Particle p = particleData[particle_id];
	ParticleInfo p_info = particleInfoData[particle_id];
	
	vec3 pressure_force = calculatePressureForce(particle_id, p.pos, vec2(p_info.density, p_info.near_density));
	vec3 viscosity_force = p_info.visc_force;
	vec3 gravity_force = gravity;
	vec3 boundary_force = vec3(0);
	
	//boundary clamping
	{
		if (p.pos.x < bounds_min.x + 0.001) {
			p.pos.x = bounds_min.x + 0.001;
			p.vel.x *= -0.1;
		}
		if (p.pos.x > bounds_max.x - 0.001) {
			p.pos.x = bounds_max.x - 0.001;
			p.vel.x *= -0.1;
		}
		if (p.pos.y < bounds_min.y + 0.001) {
			p.pos.y = bounds_min.y + 0.001;
			p.vel.y *= -0.1;
		}
		if (p.pos.y > bounds_max.y - 0.001) {
			p.pos.y = bounds_max.y - 0.001;
			p.vel.y *= -0.1;
		}
		if (p.pos.z < bounds_min.z + 0.001) {
			p.pos.z = bounds_min.z + 0.001;
			p.vel.z *= -0.1;
		}
		if (p.pos.z > bounds_max.z - 0.001) {
			p.pos.z = bounds_max.z - 0.001;
			p.vel.z *= -0.1;
		}
	}
	
	//boundary forces
	{
		if(p.pos.x - bounds_min.x < smoothing_radius) {
			boundary_force -= nearDensitySmoothingKernelSlope(p.pos.x - bounds_min.x) * vec3(1, 0, 0);
		}
		if(bounds_max.x - p.pos.x < smoothing_radius) {
			boundary_force -= nearDensitySmoothingKernelSlope(bounds_max.x - p.pos.x) * vec3(-1, 0, 0);
		}
		if(p.pos.y - bounds_min.y < smoothing_radius) {
			boundary_force -= nearDensitySmoothingKernelSlope(p.pos.y - bounds_min.y) * vec3(0, 1, 0);
		}
		if(bounds_max.y - p.pos.y < smoothing_radius) {
			boundary_force -= nearDensitySmoothingKernelSlope(bounds_max.y - p.pos.y) * vec3(0, -1, 0);
		}
		if(p.pos.z - bounds_min.z < smoothing_radius) {
			boundary_force -= nearDensitySmoothingKernelSlope(p.pos.z - bounds_min.z) * vec3(0, 0, 1);
		}
		if(bounds_max.z - p.pos.z < smoothing_radius) {
			boundary_force -= nearDensitySmoothingKernelSlope(bounds_max.z - p.pos.z) * vec3(0, 0, -1);
		}
	}
	
	vec3 force = pressure_force + viscosity_force + gravity_force + boundary_force * 20;
	if(length(force) > 200){
		force = normalize(force) * 200;
	}
	p.vel += force * dt;
	
	particleData[particle_id] = p;
}






